from models.base import Base
from models.nationality import Nationality
from models.people import People
from models.route import Route
from models.company import Company
from models.plane import Plane
from models.employee import Employee
from models.trip import Trip
from models.passenger import Passenger
from models.maintenance import Maintenance
from models.contact import Contact
from models.passenger_has_trip import passenger_has_trip
from models.employee_has_trip import employee_has_trip
from models.people_has_nacionality import people_has_nacionality